# Generated by Django 4.2.5 on 2023-10-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EstrayaApp', '0002_usertask_created_at_usertask_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='updated_at',
        ),
    ]
