# Generated by Django 4.2.5 on 2023-10-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstrayaApp', '0007_alter_skill_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
