# Generated by Django 4.2.5 on 2023-10-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstrayaApp', '0008_skill_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image_url',
            field=models.URLField(blank=True, default='https://picsum.photos/200/200'),
        ),
    ]
