# Generated by Django 4.2.5 on 2023-10-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstrayaApp', '0009_alter_skill_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image_url',
            field=models.URLField(blank=True, default='https://picsum.photos/200/200'),
        ),
    ]
