# Generated by Django 4.2.5 on 2024-02-07 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('EstrayaApp', '0010_task_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('expiry', models.DateTimeField()),
            ],
            bases=('authtoken.token',),
        ),
        migrations.AlterField(
            model_name='task',
            name='image_url',
            field=models.URLField(blank=True, default='https://picsum.photos/100'),
        ),
    ]
