# Generated by Django 4.2.5 on 2024-02-10 20:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('EstrayaApp', '0011_customtoken_alter_task_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('expiry', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=('authtoken.token',),
        ),
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
